# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDWebImage 源码学习' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDWebImage 源码学习

pod 'SDWebImage', '~> 4.0.0'

end

target 'SDWebImage 基本使用' do
    
pod 'SDWebImage', '~> 4.0.0'
pod 'SDWebImage/GIF'

end
